jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgresql
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
      threads: 4