FROM python:3.10-slim

ENV DAGSTER_HOME=/opt/dagster/dagster_home/
RUN mkdir -p $DAGSTER_HOME /opt/dagster/app
WORKDIR /opt/dagster/app

RUN apt-get update \
 && apt-get install -y --no-install-recommends git \
 && apt-get purge -y --auto-remove \
 && rm -rf /var/lib/apt/lists/*

COPY ./.docker/requirements.txt requirements.txt
RUN pip install -r ./requirements.txt

COPY ./jaffle_shop ./

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "./definitions.py"]
